export enum SectionArea {
  DOUBLE_BULL = 'DOUBLE_BULL',
  SINGLE_BULL = 'SINGLE_BULL',
  INNER_SINGLE = 'INNER_SINGLE',
  TRIPLE = 'TRIPLE',
  OUTER_SINGLE = 'OUTER_SINGLE',
  DOUBLE = 'DOUBLE',
  MISS = 'MISS'
}
